// app/components/add-dump-form/AddDumpForm.tsx
'use client';

import { useState } from 'react';

export default function AddDumpForm() {
  const [rawText, setRawText] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Server Action will be called here
    alert("Form submission is not implemented yet.");
  };

  return (
    <form onSubmit={handleSubmit} className="p-4 bg-gray-800 rounded-lg shadow-lg mb-6">
      <h2 className="text-xl font-bold mb-3 text-gray-200">Add a new Brain Dump</h2>
      <textarea
        className="w-full bg-gray-700 text-gray-200 rounded-md p-3 border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none transition"
        rows={3}
        placeholder="e.g., 'Team meeting tomorrow at 10am to discuss project X'"
        value={rawText}
        onChange={(e) => setRawText(e.target.value)}
      />
      <div className="flex justify-between items-center mt-3">
        <p className="text-xs text-gray-400">
          Press{' '}
          <kbd className="px-2 py-1 text-xs font-semibold text-gray-800 bg-gray-100 border border-gray-200 rounded-lg">
            Ctrl/Cmd
          </kbd>{' '}
          +{' '}
          <kbd className="px-2 py-1 text-xs font-semibold text-gray-800 bg-gray-100 border border-gray-200 rounded-lg">
            Enter
          </kbd>{' '}
          to submit
        </p>
        <button
          type="submit"
          disabled={loading || rawText.trim() === ''}
          className="px-5 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 disabled:bg-gray-500 disabled:cursor-not-allowed transition-colors duration-200 flex items-center"
        >
          {loading ? 'Processing...' : 'Add & Organize'}
        </button>
      </div>
    </form>
  );
}

// src/components/add-dump-form/add-dump-form.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { DataService } from '../../services/data.service';

@Component({
  selector: 'app-add-dump-form',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './add-dump-form.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AddDumpFormComponent {
  dataService = inject(DataService);
  rawText = signal('');

  async handleSubmit() {
    await this.dataService.addBrainDump(this.rawText());
    if(!this.dataService.geminiError()) {
        this.rawText.set('');
    }
  }
}

<div class="p-4 bg-gray-800 rounded-lg shadow-lg mb-6">
  <h2 class="text-xl font-bold mb-3 text-gray-200">Add a new Brain Dump</h2>
  <textarea
    class="w-full bg-gray-700 text-gray-200 rounded-md p-3 border border-gray-600 focus:ring-2 focus:ring-blue-500 focus:outline-none transition"
    rows="3"
    placeholder="e.g., 'Team meeting tomorrow at 10am to discuss project X'"
    [ngModel]="rawText()"
    (ngModelChange)="rawText.set($event)"
    (keydown.meta.enter)="handleSubmit()"
    (keydown.ctrl.enter)="handleSubmit()"
  ></textarea>
  <div class="flex justify-between items-center mt-3">
    <p class="text-xs text-gray-400">Press <kbd class="px-2 py-1 text-xs font-semibold text-gray-800 bg-gray-100 border border-gray-200 rounded-lg">Ctrl/Cmd</kbd> + <kbd class="px-2 py-1 text-xs font-semibold text-gray-800 bg-gray-100 border border-gray-200 rounded-lg">Enter</kbd> to submit</p>
    <button
      (click)="handleSubmit()"
      [disabled]="dataService.loading() || rawText().trim() === ''"
      class="px-5 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 disabled:bg-gray-500 disabled:cursor-not-allowed transition-colors duration-200 flex items-center"
    >
      @if (dataService.loading()) {
        <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        <span>Processing...</span>
      } @else {
        <span>Add & Organize</span>
      }
    </button>
  </div>
  @if (dataService.geminiError(); as error) {
    <div class="mt-3 p-3 bg-red-900 border border-red-700 text-red-200 rounded-lg">
        <p><span class="font-bold">Error:</span> {{ error }}</p>
    </div>
  }
</div>
